export const DEFAULT_LOCALE = 'en';
export const SWITCH_ORG_REQUEST = 'cap/SWITCH_ORG_REQUEST';
export const SWITCH_ORG_SUCCESS = 'cap/SWITCH_ORG_SUCCESS';
export const SWITCH_ORG_FAILURE = 'cap/SWITCH_ORG_FAILURE';
export const LOGIN_REQUEST = 'cap/LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'cap/LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'cap/LOGIN_FAILURE';

export const LOGOUT_REQUEST = 'cap/LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'cap/LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'cap/LOGOUT_FAILURE';
export const ADD_MESSAGE = 'cap/ADD_MESSAGE';
export const REMOVE_MESSAGE = 'cap/REMOVE_MESSAGE';
export const GET_USER_DATA_REQUEST = 'cap/GET_USER_DATA_REQUEST';
export const GET_USER_DATA_SUCCESS = 'cap/GET_USER_DATA_SUCCESS';
export const GET_USER_DATA_FAILURE = 'cap/GET_USER_DATA_FAILURE';

export const GET_SCHEMA_FOR_ENTITY_FAILURE = 'cap/GET_SCHEMA_FOR_ENTITY_FAILURE';
export const GET_SCHEMA_FOR_ENTITY_REQUEST = 'cap/GET_SCHEMA_FOR_ENTITY_REQUEST';
export const GET_SCHEMA_FOR_ENTITY_SUCCESS = 'cap/GET_SCHEMA_FOR_ENTITY_SUCCESS';
export const CLEAR_META_ENTITIES = 'cap/CLEAR_META_ENTITIES';
export const HIDE_TAGS = 'cap/HIDE_TAGS';
